name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_call:
    inputs:
      plan:
        description: The dist release plan
        required: false
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Test workspace
        run: cargo test --workspace --locked
